version: '3'
networks:
    network:
        driver: bridge 
       
services:
    db:
        container_name: db
        image: postgres:latest
        env_file: 
            - ./postgres/postgres.env
        ports:
            - 5433:5432
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        networks:
            - network
    
    api:
        container_name: api
        build: ./rubicon-test
        env_file:
            - ./rubicon-test/rubicon.env
        ports:
            - 3000:80
        depends_on:
            - "db"
        networks:
            - network

volumes:
    db_volume: